kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: harbor-cluster-loader
  namespace: fleet-local
spec:
  repo: https://github.com/bgregorius-rgs/devops-platform.git
  branch: main  
  targets:
  - clusterName: local
  paths:
  - "./clusters/aws/harbor"