# be sure to add all "required" values...

# amazonec2, azure, digitalocean, harvester, vsphere, custom
cloudprovider: amazonec2

# cloud provider credentials (example: aws-creds)
cloudCredentialSecretName: cc-bnlbp

# rancher manager url
rancher:
  cattle:
    url: rancher.rgs-demo.xyz

# cluster values
cluster:
  # annotations:
    # key: value
  labels:
    deploy-harbor: 'true'
  name: harbor-rke2-cluster
  config:
    systemDefaultRegistry: docker.io # default registry
    kubernetesVersion: v1.26.13+rke2r1 # https://github.com/rancher/rke2/releases
    localClusterAuthEndpoint:
      enabled: false
    # agentEnvVars:
      # - key:value
    cni: canal # canal, calico, cilium, multus,canal, multus,calico, multus,cilium
    docker: false
    disable_kube_proxy: false
    etcd_expose_metrics: false
    enableNetworkPolicy: true
    # defaultClusterRoleForProjectMembers: ''
    # defaultPodSecurityAdmissionConfigurationTemplateName: ''
    # defaultPodSecurityPolicyTemplateName: ''
    profile: '' # cis-1.6, cis-1.23
    selinux: false
    secrets_encryption: false
    write_kubeconfig_mode: 0600
    use_service_account_credentials: false
    protect_kernel_defaults: false
    cloud_provider_name: aws # aws, azure, harvester, vsphere
    # cloud_provider_config: '' # cloud provider config secret here (example: secret://fleet-default:cloudprovider)
    # kube_controller_manager_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager)
      # - kube controller manager arguments here
    # kube_scheduler_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler)
      # - kube scheduler arguments here
    # kube_apiserver_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver)
      # - kube apiserver arguments here
    # kubelet_arg: # (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet)
      # - kubelet arguments here
    registries:
      enabled: false
      # configs:
        # - name: registry.example.com
          # authConfigSecretName: registry-creds
          # caBundle: ''
          # insecureSkipVerify: false
          # tlsSecretName: ''
      # mirrors:
        # - name: docker.io
          # endpoints: ['registry.example.com']
      # rewrite:
         # "^rancher/(.*)": "mirrorproject/rancher-images/$1"
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false
        # deleteEmptyDirData: true
        # disableEviction: false
        # force: false
        # gracePeriod: -1
        # ignoreDaemonSets: true
        # ignoreErrors: false
        # skipWaitForDeleteTimeoutSeconds: 0
        # timeout: 120

# node and nodepool(s) values
nodepools:
  - name: pool-a
    quantity: 1
    etcd: true
    controlplane: true
    worker: true
    paused: false
    ami: ami-080e1f13689e07408 
    deviceName: /dev/sda1
    encryptEbsVolume: false
    endpoint: ''
    iamInstanceProfile: # required (example: rancher-iam-instance-profile) - https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
    insecureTransport: false
    instanceType: m5.xlarge # required (example: m5.2xlarge)
    region: us-east-1 # required (example: us-east-1)
    createSecurityGroup: true
    securityGroups: [''] # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
    keypairName: ''
    securityGroupReadonly: false
    sshKeyContents: ''
    subnetId: subnet-0b010a41304914b66 # required (example: subnet-123456789)
    zone: a # required (example: a)
    monitoring: false
    usePrivateAddress: true
    privateAddressOnly: true
    requestSpotInstance: false
    # spotPrice: ''
    # tags: ''
    retries: 5
    rootSize: 64
    sshUser: ubuntu
    volumeType: gp3
    vpcId: vpc-0ee9740ec41fda259 # required (example: vpc-123456789)
    useEbsOptimizedInstance: false
  - name: pool-b
    quantity: 1
    etcd: true
    controlplane: true
    worker: true
    paused: false
    ami: ami-080e1f13689e07408 
    deviceName: /dev/sda1
    encryptEbsVolume: false
    endpoint: ''
    iamInstanceProfile: # required (example: rancher-iam-instance-profile) - https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
    insecureTransport: false
    instanceType: m5.xlarge # required (example: m5.2xlarge)
    region: us-east-1 # required (example: us-east-1)
    createSecurityGroup: true
    securityGroups: [''] # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
    keypairName: ''
    securityGroupReadonly: false
    sshKeyContents: ''
    subnetId: subnet-09c447314790930d6 # required (example: subnet-123456789)
    zone: b # required (example: a)
    monitoring: false
    usePrivateAddress: true
    privateAddressOnly: true
    requestSpotInstance: false
    # spotPrice: ''
    # tags: ''
    retries: 5
    rootSize: 64
    sshUser: ubuntu
    volumeType: gp3
    vpcId: vpc-0ee9740ec41fda259 # required (example: vpc-123456789)
    useEbsOptimizedInstance: false
  - name: pool-c
    quantity: 1
    etcd: true
    controlplane: true
    worker: true
    paused: false
    ami: ami-080e1f13689e07408 
    deviceName: /dev/sda1
    encryptEbsVolume: false
    endpoint: ''
    iamInstanceProfile: # required (example: rancher-iam-instance-profile) - https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon
    insecureTransport: false
    instanceType: m5.xlarge # required (example: m5.2xlarge)
    region: us-east-1 # required (example: us-east-1)
    createSecurityGroup: true
    securityGroups: [''] # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-requirements/port-requirements
    keypairName: ''
    securityGroupReadonly: false
    sshKeyContents: ''
    subnetId: subnet-0006a00914b04aa7d # required (example: subnet-123456789)
    zone: c # required (example: a)
    monitoring: false
    usePrivateAddress: true
    privateAddressOnly: true
    requestSpotInstance: false
    # spotPrice: ''
    # tags: ''
    retries: 5
    rootSize: 64
    sshUser: ubuntu
    volumeType: gp3
    vpcId: vpc-0ee9740ec41fda259 # required (example: vpc-123456789)
    useEbsOptimizedInstance: false

# addons values
addons:
  monitoring:
    enabled: false
    # version: 103.0.3+up45.31.1
    # values:
      # values here

  longhorn:
    enabled: true
    # version: 103.2.1+up1.5.3
    # values:
      # values here

  neuvector:
    enabled: false
    # version: 103.0.1+up2.7.1
    # values:
      # values here