apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  commonName: "rgs-demo.xyz"
  dnsNames:
  - "rgs-demo.xyz"
  - "*.rgs-demo.xyz"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-rancher-ingress